name: Docs
on:
  push:
    tags: [ "v*" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: chainguard-actions/actions-checkout@d1f1061cdaee56aa3a3bc3deb86b67b1db772dd6 # v6.0.2
      with:
        persist-credentials: false
    - name: Set up Docker Buildx
      uses: chainguard-actions/docker-setup-buildx-action@b6beb8a80a92c55017146dc002f047479d776a98 # v4.1.0
    - name: Build and deploy mkdocs site
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        make build-docs
        sudo chown -R ${UID}:${UID} docs
        make deploy-docs

