name: Docs
on:
  push:
    tags: [ "v*" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9
    - name: Build and deploy mkdocs site
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        make build-docs
        sudo chown -R ${UID}:${UID} docs
        make deploy-docs

